---
date: "3/13/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, echo=FALSE, results='hide'}
library(pacman) # Package manager (installs and loads)
p_load(googledrive, # Main package
       dplyr, # For cleaning and wrangling
       magrittr, # For pipes
       kableExtra, # For making pretty tables
       ggplot2)    # Pretty graphs/visuals

# Downloading file (set overwrite = F if downloading for first time)
drive_download("scooper_form_responses", type = "csv", overwrite = T)
scooper_df = readr::read_csv("scooper_form_responses.csv")

scooper = scooper_df %>% # To preserve original data frame
   tidyr::separate(Timestamp, c("Date", "Time"),
                   sep = " ") %>% # Separating at column spacing
   rename("Stool" = "Shit") %>% # Renaming for civility's sake
   mutate(both =       # Creating an variable for outings with both dogs
             if_else(`Which Dog?`=="Both", TRUE, FALSE),
          id = row_number())

S_scoop = scooper %>% # The 'scoop' on our Great Dane
   group_by(`Which Dog?`) %>%
   filter(`Which Dog?`=="Both"|`Which Dog?`=="Siobhan") %>%
   ungroup() %>%
   select(-c(`Which Dog?`)) # Removing now-irrelevant column

B_scoop = scooper %>% # The 'scoop' on our Wolfhound
   group_by(`Which Dog?`) %>%
   filter(`Which Dog?`=="Both"|`Which Dog?`=="Braonin") %>%
   ungroup()%>%
   select(-c(`Which Dog?`)) # Removing now-irrelevant column

```

```{r echo=FALSE}

## Last outing records

B_last_outing = B_scoop %>% filter(id == (last(B_scoop$id)))
S_last_outing = S_scoop %>% filter(id == (last(S_scoop$id)))

# Condensing down to relevant information to fit within well-formatted table

# Shorter date display
B_last_outing$Date = substr(B_last_outing$Date,1,nchar(B_last_outing$Date)-5)
S_last_outing$Date = substr(S_last_outing$Date,1,nchar(S_last_outing$Date)-5)

# Removing unwanted variables for display
B_last_outing %<>%
   select(-c("Time","Indicator Value","Time-Out","Notes","both"))

S_last_outing %<>%
   select(-c("Time","Indicator Value","Time-Out","Notes","both"))
```




```{r echo=FALSE}
# Cleaning for pretties presentation

B_table = B_last_outing %>% select(-c("id")) %>%
   mutate(Urine    = grepl("1_B",B_last_outing$Urine),
          Stool    = grepl("1_B",B_last_outing$Stool))%>%
   rename(" 💩 " = "Stool",
          " 💦 " = "Urine")%>%
   tidyr::separate(`Time-In`, c("Time", "AM/PM"),
                   sep = " ")%>%
   mutate(Time   = gsub('.{0,3}$', '', .$Time),
          "🌚/🌞"= if_else("AM/PM"=="AM","🌞","🌚"),
          " 💩 " = if_else(.[[5]]==TRUE,"💩"," "),
          " 💦 "= if_else(.[[4]]==TRUE,"💦"," "))%>%
   rename(" "= "🌚/🌞")
B_table2 = B_table[, c(1,6,2,4,5)]
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
kbl(B_table2, col.names = NULL, longtable = T)
```




